package ventanas;
import java.sql.*;
import clases.Conexion;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

//Aqui tienes que ser muy especifico en cuanto a que paquete quieres
//implementar y que clase!!!!!!!!
import com.itextpdf.text.Document;

//En este caso importe un subpaquete por eso coloque el pdf
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

//ESta clase como puedes leer pertece a JAVA!!!!!

import java.io.FileOutputStream;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfWriter;

import javax.swing.JOptionPane;
/**
 *
 * @author ruben
 */
public class Administrador extends javax.swing.JFrame {
    
    String email, nombre_usuario;
    public static int sesion_usuario;
    
    public Administrador() {
        initComponents();
        email = Login.email;
        sesion_usuario = 1;
        
        setSize(650,430);
        setResizable(false);
        setTitle("Administrador - Sesion de " + email);
        
        setTitle("Administrador");
        setLocationRelativeTo(null);
        
        //ESte metodo te permite matar procesos en segundo plano
        //Cuando tu cierres la interfaz esta se va a seguir ejecutando y por eso es que 
        //lo cierras
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        //Fondo de la interfaz //
        //netbeans guarda tus imagenes dentro de una carpeta src
        ImageIcon wallpaper = new ImageIcon("src/images/Wallpaper2.png");
        //La clase Icon te permite acomodar o ajustar la imagen en la interfaz.
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(JLabel_wallpaper.getWidth(), JLabel_wallpaper.getHeight(), Image.SCALE_DEFAULT));
           
        JLabel_wallpaper.setIcon(icono);

        //este metodo es para asegurar los 
        //cambios
        this.repaint();
        
        try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select username from Users where email = '" + email + "'");
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
               nombre_usuario = rs.getString("username");
               JLabel_NombreUsuario.setText("Bienvenido " + nombre_usuario);
               
            }
        }catch(Exception e){
            System.err.println("Error en la conexion desde la ventana administrador");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButtonRegistrarUsuario = new javax.swing.JButton();
        JLabel_NombreUsuario = new javax.swing.JLabel();
        JButton_GestionarUsuarios = new javax.swing.JButton();
        JButton_Recomendaciones = new javax.swing.JButton();
        JButton_Contaduria = new javax.swing.JButton();
        JButton_Ventas = new javax.swing.JButton();
        JButton_CrealoTu = new javax.swing.JButton();
        JLabelRegistrarUser = new javax.swing.JLabel();
        jLabelAdministrarUsers = new javax.swing.JLabel();
        jLabelRecomendaciones = new javax.swing.JLabel();
        JLabelAdministracion = new javax.swing.JLabel();
        jLabelVentas = new javax.swing.JLabel();
        jLabelCrealoTu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JButtonRegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Registrar.png"))); // NOI18N
        JButtonRegistrarUsuario.setText("jButton1");
        JButtonRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, 100));

        JLabel_NombreUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JLabel_NombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_NombreUsuario.setText("Bienvenido");
        getContentPane().add(JLabel_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 30));

        JButton_GestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AdministrarUsers.png"))); // NOI18N
        JButton_GestionarUsuarios.setText("jButton1");
        JButton_GestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_GestionarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(JButton_GestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, 100));

        JButton_Recomendaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Recomendaciones.png"))); // NOI18N
        JButton_Recomendaciones.setText("jButton1");
        JButton_Recomendaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_RecomendacionesActionPerformed(evt);
            }
        });
        getContentPane().add(JButton_Recomendaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 120, 100));

        JButton_Contaduria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Contaduria.png"))); // NOI18N
        JButton_Contaduria.setText("jButton1");
        JButton_Contaduria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ContaduriaActionPerformed(evt);
            }
        });
        getContentPane().add(JButton_Contaduria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 120, 100));

        JButton_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ventas.png"))); // NOI18N
        JButton_Ventas.setText("jButton1");
        JButton_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_VentasActionPerformed(evt);
            }
        });
        getContentPane().add(JButton_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 120, 100));

        JButton_CrealoTu.setBackground(new java.awt.Color(181, 31, 31));
        JButton_CrealoTu.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JButton_CrealoTu.setForeground(new java.awt.Color(255, 255, 255));
        JButton_CrealoTu.setText("PDF");
        JButton_CrealoTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_CrealoTuActionPerformed(evt);
            }
        });
        getContentPane().add(JButton_CrealoTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 140, 100));

        JLabelRegistrarUser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JLabelRegistrarUser.setForeground(new java.awt.Color(255, 255, 255));
        JLabelRegistrarUser.setText("Registrar User");
        getContentPane().add(JLabelRegistrarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabelAdministrarUsers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelAdministrarUsers.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdministrarUsers.setText("Administrar User");
        getContentPane().add(jLabelAdministrarUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabelRecomendaciones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelRecomendaciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRecomendaciones.setText("Recomendaciones");
        getContentPane().add(jLabelRecomendaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        JLabelAdministracion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JLabelAdministracion.setForeground(new java.awt.Color(255, 255, 255));
        JLabelAdministracion.setText("Administracion");
        getContentPane().add(JLabelAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabelVentas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVentas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVentas.setText("Ventas");
        getContentPane().add(jLabelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jLabelCrealoTu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCrealoTu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCrealoTu.setText("Generar PDF");
        getContentPane().add(jLabelCrealoTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        jLabel1.setText("Creado por: Future Tech");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));
        getContentPane().add(JLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRegistrarUsuarioActionPerformed
       
        RegistrarUsuarios registrarusuarios = new RegistrarUsuarios();
        registrarusuarios.setVisible(true);
    }//GEN-LAST:event_JButtonRegistrarUsuarioActionPerformed

    private void JButton_GestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_GestionarUsuariosActionPerformed
       
        GestionarUsuarios gs = new GestionarUsuarios();
        gs.setVisible(true);
        
    }//GEN-LAST:event_JButton_GestionarUsuariosActionPerformed

    private void JButton_CrealoTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_CrealoTuActionPerformed
       
         Document documento = new Document();        
         
         try{
         
            String ruta = System.getProperty("user.home");
            
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Reporte de Ventas.pdf"));
            
            documento.open();
            
            
            PdfPTable tabla = new PdfPTable(7);
            
            tabla.addCell("Nombre_Comprador");
            tabla.addCell("Telefono");
            tabla.addCell("Correo");
            tabla.addCell("Precio vendido");
            tabla.addCell("Tipo de Amplificador");
            tabla.addCell("Wattts");
            tabla.addCell("Fecha");
            
            try{
             
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from ventas");
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
              
                do{
                tabla.addCell(rs.getString(1));
                tabla.addCell(rs.getString(2));
                tabla.addCell(rs.getString(3));
                tabla.addCell(rs.getString(4));
                tabla.addCell(rs.getString(5));
                tabla.addCell(rs.getString(6));
                tabla.addCell(rs.getString(7));
                } while(rs.next());      
            } 
            
            documento.add(tabla);
            
            JOptionPane.showMessageDialog(null, "Reporte de ventas creado con Exito");
           
            
            } catch(Exception e){
                
            }
            
            //ES importantisimo que cierres el documento, ya que si no lo haces no va a 
            //servir
            documento.close();
            
         } catch(Exception e){
             
             System.err.println("Error al crear el pdf " + e);
         
         }
        
        
        
    }//GEN-LAST:event_JButton_CrealoTuActionPerformed

    private void JButton_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_VentasActionPerformed
       
        Ventas puente0 = new Ventas();
        puente0.setVisible(true);
        
        
        
    }//GEN-LAST:event_JButton_VentasActionPerformed

    private void JButton_ContaduriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ContaduriaActionPerformed
          
          Administracion puente0 = new Administracion();
          puente0.setVisible(true);
          
          
    }//GEN-LAST:event_JButton_ContaduriaActionPerformed

    private void JButton_RecomendacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_RecomendacionesActionPerformed
      
        Recomendaciones puente0 = new Recomendaciones();
        puente0.setVisible(true);
        
    }//GEN-LAST:event_JButton_RecomendacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonRegistrarUsuario;
    private javax.swing.JButton JButton_Contaduria;
    private javax.swing.JButton JButton_CrealoTu;
    private javax.swing.JButton JButton_GestionarUsuarios;
    private javax.swing.JButton JButton_Recomendaciones;
    private javax.swing.JButton JButton_Ventas;
    private javax.swing.JLabel JLabelAdministracion;
    private javax.swing.JLabel JLabelRegistrarUser;
    private javax.swing.JLabel JLabel_NombreUsuario;
    private javax.swing.JLabel JLabel_wallpaper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdministrarUsers;
    private javax.swing.JLabel jLabelCrealoTu;
    private javax.swing.JLabel jLabelRecomendaciones;
    private javax.swing.JLabel jLabelVentas;
    // End of variables declaration//GEN-END:variables
}
