package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class Login extends javax.swing.JFrame {

    public static String user = "";
    String pass = "";

    /**
     * Creates new form Login
     */
    
    public Login() {

        initComponents();
        setSize(400, 550);
        setResizable(false);
        setTitle("Acceso al Programa");
        setLocationRelativeTo(null);

        //Fondo de la interfaz //
        //netbeans guarda tus imagenes dentro de una carpeta src
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaper.jpg");
        //La clase Icon te permite acomodar o ajustar la imagen en la interfaz.
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(JLabel_wallpaper.getWidth(), JLabel_wallpaper.getHeight(), Image.SCALE_DEFAULT));

        JLabel_wallpaper.setIcon(icono);

        //este metodo es para asegurar los 
        //cambios
        this.repaint();

        //Logo de Compañia
        ImageIcon wallpaper_logo = new ImageIcon("");

    }

    /**s
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        Button_Acceder = new javax.swing.JButton();
        txt_user = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        JLabel_Footer = new javax.swing.JLabel();
        JLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setText("jLabel1");
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        Button_Acceder.setBackground(new java.awt.Color(185, 234, 252));
        Button_Acceder.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        Button_Acceder.setForeground(new java.awt.Color(19, 99, 181));
        Button_Acceder.setText("Acceder");
        Button_Acceder.setBorder(null);
        Button_Acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AccederActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 412, 210, 40));

        txt_user.setBackground(new java.awt.Color(185, 234, 252));
        txt_user.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_user.setForeground(new java.awt.Color(19, 99, 169));
        txt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_user.setToolTipText("");
        txt_user.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 320, 210, 30));

        txt_password.setBackground(new java.awt.Color(185, 234, 252));
        txt_password.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_password.setForeground(new java.awt.Color(19, 99, 169));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 360, 210, 30));

        JLabel_Footer.setForeground(new java.awt.Color(0, 0, 0));
        JLabel_Footer.setText("Created by: Amplified Cube");
        getContentPane().add(JLabel_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));
        getContentPane().add(JLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_AccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AccederActionPerformed

        user = txt_user.getText().trim();
        pass = txt_password.getText().trim();

        if (!user.equals("") || !pass.equals("")) {

            try {

                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select tipo_nivel, estatus from usuarios where username = '" + user
                        + "' and password = '" + pass + "'");

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {

                    String tipo_nivel = rs.getString("tipo_nivel");
                    String estatus = rs.getString("estatus");

                    if (tipo_nivel.equalsIgnoreCase("Administrador") && estatus.equalsIgnoreCase("Activo")) {
                        //ESte metodo permite que el JFrame sea destruido
                        //y se ejecute lo siguiente
                        dispose();
                        new Administrador().setVisible(true);

                    } else if (tipo_nivel.equalsIgnoreCase("Contaduria") && estatus.equalsIgnoreCase("Activo")) {

                        dispose();
                        new Contador().setVisible(true);

                    } else if (tipo_nivel.equalsIgnoreCase("Vendedor") && estatus.equalsIgnoreCase("Activo")) {

                        dispose();
                        new Vendedor().setVisible(true);

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Datos de acceso incorrectos");
                    txt_user.setText("");
                    txt_password.setText("");

                }

            } catch (SQLException e) {

                System.err.println("Error en el boton acceder ");
                JOptionPane.showMessageDialog(null, "¡Error al iniciar sesion!\n"
                        + "comunicate con el administrador");

            }

        } else {

            JOptionPane.showMessageDialog(null, "Tienes que llenar los campos");

        }


    }//GEN-LAST:event_Button_AccederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Acceder;
    private javax.swing.JLabel JLabel_Footer;
    private javax.swing.JLabel JLabel_wallpaper;
    private javax.swing.JLabel Logo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
