/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.sql.*;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

//Esta clase nos sirve para capturar algun error al momento
//de generar el documento

import java.io.FileOutputStream;
import javax.swing.JOptionPane;

//Por eso es que en el catch exception se coloca IO exception
import com.itextpdf.text.DocumentException;


public class Vendedor extends javax.swing.JFrame {

    /**
     * Creates new form Vendedor
     */
    public Vendedor() {
        
        
        
        
        initComponents();
        
        String user = Login.user;
        
        JLabel_titulo.setText("Bienvenido " + user);
        
        setResizable(false);
        
        setTitle("Vendedor");
        setLocationRelativeTo(null);
        //Fondo de la interfaz //
        //netbeans guarda tus imagenes dentro de una carpeta src
        ImageIcon wallpaper = new ImageIcon("src/images/Wallpaper2.png");
        //La clase Icon te permite acomodar o ajustar la imagen en la interfaz.
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(JLabel_wallpaper.getWidth(), JLabel_wallpaper.getHeight(), Image.SCALE_DEFAULT));
           
        JLabel_wallpaper.setIcon(icono);

        //este metodo es para asegurar los 
        //cambios
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButton_Ventas1 = new javax.swing.JButton();
        JButton_Recomendaciones1 = new javax.swing.JButton();
        JButton_CrealoTu1 = new javax.swing.JButton();
        JLabel_titulo = new javax.swing.JLabel();
        JLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JButton_Ventas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ventas.png"))); // NOI18N
        JButton_Ventas1.setText("jButton1");
        JButton_Ventas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_Ventas1ActionPerformed(evt);
            }
        });
        getContentPane().add(JButton_Ventas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 100));

        JButton_Recomendaciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Recomendaciones.png"))); // NOI18N
        JButton_Recomendaciones1.setText("jButton1");
        JButton_Recomendaciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_Recomendaciones1ActionPerformed(evt);
            }
        });
        getContentPane().add(JButton_Recomendaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 120, 100));

        JButton_CrealoTu1.setBackground(new java.awt.Color(181, 32, 32));
        JButton_CrealoTu1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JButton_CrealoTu1.setForeground(new java.awt.Color(255, 255, 255));
        JButton_CrealoTu1.setText("PDF");
        JButton_CrealoTu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_CrealoTu1ActionPerformed(evt);
            }
        });
        getContentPane().add(JButton_CrealoTu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 140, 100));

        JLabel_titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_titulo.setText("Bienvenido ");
        getContentPane().add(JLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, -1));
        getContentPane().add(JLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_CrealoTu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_CrealoTu1ActionPerformed
         
       Document documento = new Document();
       
       try{
           
           //Este metodo te ayuda a conseguir la direccion de el usuario
           //para posteriormente poder decidir donde lo quieres guardar
           String ruta = System.getProperty("user.home");
           
           //Aqui solo estoy indicando en donde quiero que se guarde mi archivo
           //con la variable String consigo la ruita de mi user y con la clase padWriter otneog el
           //metodo para crear una instancia y despues indicar donde quiero que se guarde el documento.
           PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Reporte De Ventas.pdf"));
           
           documento.open();
           
           PdfPTable tabla = new PdfPTable(7);
           
           tabla.addCell("Nombre del Comprador");
           tabla.addCell("Telefono");
           tabla.addCell("Correo");
           tabla.addCell("Precio vendido del Amplificador");
           tabla.addCell("Tipo de Ampĺificador");
           tabla.addCell("Wattts");
           tabla.addCell("Fecha");
           
           
           try{
           
               Connection cn = Conexion.conectar();
               PreparedStatement pst = cn.prepareStatement("select * from ventas");
               
               ResultSet rs = pst.executeQuery();
               
               if(rs.next()){
                   
                   do{
                      
                       //El salto de fila lo hace automaticamente
                       //mi clase tabla
                       
                       //No te confundas aqui dice agregar celda haciendo referencia a cada espacio
                       //generado
                       tabla.addCell(rs.getString(1));
                       tabla.addCell(rs.getString(2));
                       tabla.addCell(rs.getString(3));
                       tabla.addCell(rs.getString(4));
                       tabla.addCell(rs.getString(5));
                       tabla.addCell(rs.getString(6));
                       tabla.addCell(rs.getString(7));
                       
                       
                       
                   } while(rs.next());
                     
                    documento.add(tabla);
                   
               }
               
               
           } catch(Exception e){
               
           }
           
           documento.close();
           JOptionPane.showMessageDialog(null, "Reporte de ventas creado ");
           
       } catch(Exception e){
           
       }
        
        
        
        
    }//GEN-LAST:event_JButton_CrealoTu1ActionPerformed

    private void JButton_Ventas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_Ventas1ActionPerformed
       
        Ventas puente0 = new Ventas();
        puente0.setVisible(true);
        
    }//GEN-LAST:event_JButton_Ventas1ActionPerformed

    private void JButton_Recomendaciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_Recomendaciones1ActionPerformed
       
        Recomendaciones puente0 = new Recomendaciones();
        puente0.setVisible(true);
    }//GEN-LAST:event_JButton_Recomendaciones1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_CrealoTu1;
    private javax.swing.JButton JButton_Recomendaciones1;
    private javax.swing.JButton JButton_Ventas1;
    private javax.swing.JLabel JLabel_titulo;
    private javax.swing.JLabel JLabel_wallpaper;
    // End of variables declaration//GEN-END:variables
}
