/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import java.sql.*;
import clases.Conexion;

/**
 *
 * @author ruben
 */
public class Ventas extends javax.swing.JFrame {
//En la base de datos se tiene que agreagar la fecha y agregar un sistema para saber quien esta agregando la compra

    public Ventas() {
        initComponents();
        setLocationRelativeTo(null);
        String user = Login.email;
        setResizable(false);
        JLabel_Titulo.setText("Bienvenido " + user);

        ImageIcon wallpaper = new ImageIcon("src/images/Wallpaper2.png");
        Icon fondo = new ImageIcon(wallpaper.getImage().getScaledInstance(JLabel_Wallpaper.getWidth(), JLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));

        JLabel_Wallpaper.setIcon(fondo);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel_Titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_nombrecomprador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_watts = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_tipo = new javax.swing.JTextField();
        JLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabel_Titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        JLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Titulo.setText("JLABEL");
        getContentPane().add(JLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 590, 30));

        jButton1.setBackground(new java.awt.Color(185, 234, 252));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Agregar Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 320, 90));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Del Comprador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        txt_nombrecomprador.setBackground(new java.awt.Color(185, 234, 252));
        txt_nombrecomprador.setForeground(new java.awt.Color(19, 99, 169));
        getContentPane().add(txt_nombrecomprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio Vendido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        txt_telefono.setBackground(new java.awt.Color(185, 234, 252));
        txt_telefono.setForeground(new java.awt.Color(19, 99, 169));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono del Comprador");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txt_correo.setBackground(new java.awt.Color(185, 234, 252));
        txt_correo.setForeground(new java.awt.Color(19, 99, 169));
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 210, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo del Comprador");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        txt_precio.setBackground(new java.awt.Color(185, 234, 252));
        txt_precio.setForeground(new java.awt.Color(19, 99, 169));
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 210, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de Venta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 140, -1));

        txt_watts.setBackground(new java.awt.Color(185, 234, 252));
        txt_watts.setForeground(new java.awt.Color(19, 99, 169));
        getContentPane().add(txt_watts, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 210, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de Amplificador");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 180, -1));

        txt_fecha.setBackground(new java.awt.Color(185, 234, 252));
        txt_fecha.setForeground(new java.awt.Color(19, 99, 169));
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 210, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad de Watts");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 170, -1));

        txt_tipo.setBackground(new java.awt.Color(185, 234, 252));
        txt_tipo.setForeground(new java.awt.Color(19, 99, 169));
        getContentPane().add(txt_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 210, 30));
        getContentPane().add(JLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 690, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String nombre_comprador = txt_nombrecomprador.getText().trim();
        String telefono = txt_telefono.getText().trim();
        String correo = txt_correo.getText().trim();
        String precio = txt_precio.getText().trim();
        String tipo = txt_tipo.getText().trim();
        String watts = txt_watts.getText().trim();
        String fecha = txt_fecha.getText().trim();
        String watts2 = txt_watts.getText().trim();

        if (!nombre_comprador.equals("") && !telefono.equals("") && !correo.equals("") && !precio.equals("") && !tipo.equals("") && !watts.equals("") && !fecha.equals("")) {

            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("insert into ventas values(?,?,?,?,?,?,?,?)");
                pst.setString(1, nombre_comprador);
                pst.setString(2, telefono);
                pst.setString(3, correo);
                pst.setString(4, precio);
                pst.setString(5, tipo);
                pst.setString(6, watts);
                pst.setString(7, fecha);
                pst.setInt(8,0);
                
                pst.executeUpdate();
                
                PreparedStatement pst2 = cn.prepareStatement("insert into amplis values(?,?,?)");
                pst2.setInt(1, 0);
                pst2.setString(2, tipo);
                pst2.setString(3, watts2);
                
                pst2.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Registro de compra Exitoso");
               
                dispose();
               
            } catch (Exception e) {

                System.err.println("Error al registrar la venta" + e);
                JOptionPane.showMessageDialog(null, "Error al registrar la venta comunicate con el administrador ", "Error", JOptionPane.WARNING_MESSAGE);
               
                
            }
            
               

        } else {
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos");

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_Titulo;
    private javax.swing.JLabel JLabel_Wallpaper;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_nombrecomprador;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_tipo;
    private javax.swing.JTextField txt_watts;
    // End of variables declaration//GEN-END:variables

 


}
